background #200933
foreground #8BA7A7
cursor #8BA7A7
cursor_text_color #282A36
selection_background #463465
selection_foreground #8BA7A7

# Black
color0 #241B2F
color8 #495495

# Red
color1 #FE4450
color9 #FE4450

# Green
color2 #72F1B8
color10 #72F1B8

# Yellow
color3 #FFCC00
color11 #FFCC00

# Blue
color4 #61E2FF
color12 #61E2FF

# Magenta
color5 #FC199A
color13 #AF6DF9

# Cyan
color6 #61E2FF
color14 #61E2FF

# White
color7 #8BA7A7
color15 #8BA7A7
