font_size 14.0
# font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font ExtraBold

font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font Extra Bold
# bold_italic_font JetBrainsMono Nerd Font Extra Bold Italic

enable_audio_bell no
# disable_ligatures never

background #0f111b
foreground #ecf0c1
cursor #ecf0c1
selection_background #686f9a
color0 #000000
color8 #686f9a
color1 #e33400
color9 #e33400
color2 #5ccc96
color10 #5ccc96
color3 #b3a1e6
color11 #b3a1e6
color4 #00a3cc
color12 #00a3cc
color5 #f2ce00
color13 #f2ce00
color6 #7a5ccc
color14 #7a5ccc
color7 #686f9a
color15 #f0f1ce
selection_foreground #ffffff
