font_size 13.0
# font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font ExtraBold

font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font Extra Bold
# bold_italic_font JetBrainsMono Nerd Font Extra Bold Italic

enable_audio_bell no
# disable_ligatures never

# Color scheme
# include spaceduck-theme.conf
include fluoromachine-theme.conf
