font_size 9.0
# font_size 13.0
# font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font ExtraBold

font_family      JetBrainsMono Nerd Font
# bold_font        JetBrainsMono Nerd Font Extra Bold
# bold_italic_font JetBrainsMono Nerd Font Extra Bold Italic

enable_audio_bell no
confirm_os_window_close 0
close_on_child_death yes
# disable_ligatures never

# Color scheme
# include spaceduck-theme.conf
include fluoromachine-theme.conf
# clipboard_control write-clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary
shell /usr/bin/nu
