# -*- conf -*-
font=JetBrainsMono Nerd Font Mono:style=Bold:size=9
font-bold=JetBrainsMono Nerd Font Mono:style=ExtraBold:size=9
font-italic=JetBrainsMono Nerd Font Mono:style=Bold Italic:size=9
font-bold-italic=JetBrainsMono Nerd Font Mono:style=ExtraBold Italic:size=9

include=~/.config/foot/font.ini

shell=/usr/bin/nu
selection-target=both
pad=0x0 center-when-maximized-and-fullscreen
include=/home/tanjiro/.config/foot/fluoromachine.ini

[security]
osc52=enabled

[bell]
system=no
urgent=no
notify=no
visual=no

[csd]
border-color=200933
button-color=200933
