terminal:
    command: foot
tui_apps:
    - nvim
    - vim
    - nano
    - htop
    - lazygit
    - pulsemixer
    - bluetuith
    - cava
    - vis 
    - pulsetui
    - termpicker
    - alarm
behavior:
    closeOnLossOfFocus: true
