terminal:
    command: foot
tui_apps:
    - nvim
    - vim
    - nano
    - htop
    - lazygit
    - pulsemixer
    - bluetuith
    - bluetui
    - cava
    - vis 
    - pulsetui
    - termpicker
    - alarm
    - bang
behavior:
    closeOnLossOfFocus: true
