terminal:
    command: kitty
    args:
        - -e
tui_apps:
    - nvim
    - vim
    - nano
    - htop
    - lazygit
    - pulsemixer
    - bluetuith
    - cava
    - vis 
    - pulsetui
    - termpicker
behavior:
    closeOnLossOfFocus: false
