"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

# [username]
# show_always = true

# [hostname]
# ssh_only = false

[directory]
truncation_length = 0

[golang]
format = '[$symbol($version )]($style)'

[bun]
format = '[$symbol($version )]($style)'
