;==========================================================
; Fluoromachine Color Scheme for Polybar
;==========================================================

[colors]
background = #200933
background-alt = #1A0726
foreground = #8BA7A7
primary = #72F1B8
secondary = #AF6DF9
alert = #FE4450
disabled = #495495
border-color = #61E2FF
