;==========================================================
; SpaceDuck Color Scheme for Polybar
;==========================================================

[colors]
background = #0f111b
background-alt = #000000
foreground = #ecf0c1
primary = #5ccc96
secondary = #8ABEB7
alert = #e33400
disabled = #4e5173
border-color = #00a3cc

